# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-06
# ---------------------------------------------------------------

"""
Task ID: 2f6f32f6
Difficulty: medium

=== Tags ===
- Concentric

=== Description ===
The input grid contains concentric color layers centered around the grid's
geometric center, where each layer (defined by its distance from the center)
consists of a single uniform color. The output grid reverses the order of these
colors such that the innermost layer (closest to the center) becomes the
outermost color, and the outermost layer becomes the innermost color, with all
intermediate layers maintaining their relative spatial positions but in reversed
color sequence. For example, if the input layers (from inner to outer) are
colored [Yellow, Orange, Red], the output layers (from inner to outer) will be
[Red, Orange, Yellow]. This transformation requires identifying the concentric
structure through visual pattern recognition rather than numerical analysis,
making it a medium-difficulty task that relies on spatial reasoning and color-
layer ordering.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

def generate():
    n = random.choice([3,5,7,9,11,13,15,17])
    center = n // 2
    max_d = n // 2
    num_layers = max_d + 1
    colors = random.sample(range(1,10), num_layers)
    input_grid = [[0] * n for _ in range(n)]
    for r in range(n):
        for c in range(n):
            d = max(abs(r - center), abs(c - center))
            input_grid[r][c] = colors[d]
    output_grid = [[0] * n for _ in range(n)]
    for r in range(n):
        for c in range(n):
            d = max(abs(r - center), abs(c - center))
            output_grid[r][c] = colors[max_d - d]
    return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    n = len(input_grid)
    center = n // 2
    max_d = n // 2
    colors = []
    for d in range(max_d + 1):
        r = center - d
        c = center
        colors.append(input_grid[r][c])
    reversed_colors = colors[::-1]
    output_grid = [[0] * n for _ in range(n)]
    for r in range(n):
        for c in range(n):
            d = max(abs(r - center), abs(c - center))
            output_grid[r][c] = reversed_colors[d]
    return output_grid
