# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-11
# ---------------------------------------------------------------

"""
Task ID: 730abd41
Difficulty: easy

=== Tags ===
- Pairwise analogy
- Pattern modification
- Adapt image to grid

=== Description ===
The task involves transforming an input grid into an output grid by reversing
each row. For each row in the input grid, the elements are reordered such that
the first element becomes the last, the second becomes the second last, and so
on. This transformation is a simple pattern modification where each element in a
row is paired with its mirror position across the row's center, and their
positions are swapped. The input grids are designed to have at least two columns
to ensure the reversal results in a different output grid. The output grid is
thus the horizontally mirrored version of the input grid, demonstrating a clear
pairwise analogy between corresponding elements in each row.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random
import common

def generate():
    while True:
        width = random.randint(2, 30)
        height = random.randint(1, 30)
        input_grid = common.grid(width, height, 0)
        for r in range(height):
            for c in range(width):
                input_grid[r][c] = random.randint(0, 9)
        output_grid = [row[::-1] for row in input_grid]
        if input_grid != output_grid:
            return {
                "input": input_grid,
                "output": output_grid
            }


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input):
    return [row[::-1] for row in input]
