# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-02
# ---------------------------------------------------------------

"""
Task ID: 54296311
Difficulty: easy

=== Tags ===
- Associate colors to colors
- Take complement
- Project shadow
- Associate patterns to colors

=== Description ===
The task involves transforming each color in the input grid to its complement
color, where the complement of a color `c` is defined as `9 - c`. For example,
color `0` becomes `9`, color `1` becomes `8`, and so on. This transformation
follows a direct one-to-one association between input and output colors,
satisfying the "Associate colors to colors" and "Take complement" tags. The
"Project shadow" tag describes the visual effect of inverting colors, as if each
pixel's color casts a complementary shadow. The "Associate patterns to colors"
tag refers to the consistent mapping applied across all pixels, regardless of
their position or arrangement in the grid, ensuring the transformation is
pattern-agnostic and purely based on color values. The output grid is generated
by applying this simple complement rule to every pixel in the input grid.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

def generate():
    width = random.randint(1, 30)
    height = random.randint(1, 30)
    input_grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
    output_grid = [[9 - cell for cell in row] for row in input_grid]
    return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    return [[9 - cell for cell in row] for row in input_grid]
