# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-11
# ---------------------------------------------------------------

"""
Task ID: 4a5d3559
Difficulty: easy

=== Tags ===
- Grid coloring
- Pattern alignment
- Associate colors to bools

=== Description ===
Each input grid contains a visual pattern formed by a specific target color
(e.g., gray represented as 5 in numerical form). The output grid preserves this
target color exactly where it appears in the input, while converting all other
colors to black (represented as 0). The target color remains consistent across
all examples, and the output visualizes the input's pattern as a binary
mask—only the target color's positions remain visible, with everything else
rendered black. This transformation requires recognizing the target color and
applying a simple color filter, making it visually intuitive and suitable for an
"easy" difficulty.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

target_color = 5

def generate():
    w = random.randint(1, 30)
    h = random.randint(1, 30)
    grid = [[random.randint(0, 9) for _ in range(w)] for _ in range(h)]
    
    # Ensure target_color is present
    if target_color not in [cell for row in grid for cell in row]:
        r, c = random.randint(0, h-1), random.randint(0, w-1)
        grid[r][c] = target_color
    
    # Ensure there's at least one non-zero non-target cell
    has_non_zero_non_target = any(cell != 0 and cell != target_color for row in grid for cell in row)
    if not has_non_zero_non_target:
        for r in range(h):
            for c in range(w):
                if grid[r][c] == 0 or grid[r][c] == target_color:
                    new_color = random.choice([x for x in range(1, 10) if x != target_color])
                    grid[r][c] = new_color
                    break
            else:
                continue
            break
    
    output_grid = [[target_color if cell == target_color else 0 for cell in row] for row in grid]
    return {
        "input": grid,
        "output": output_grid
    }


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input):
    target_color = 5
    return [[target_color if cell == target_color else 0 for cell in row] for row in input]
