# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-07
# ---------------------------------------------------------------

"""
Task ID: 5bc3f2f1
Difficulty: easy

=== Tags ===
- Detect background color

=== Description ===
Each input grid contains a dominant background color that appears more
frequently than any other color, along with smaller foreground elements of
different colors. The output grid is a uniform grid where every cell is filled
with the background color, determined by the most frequent color in the input.
This transformation requires recognizing the background color through frequency
analysis, resulting in an output that is visually distinct from the input due to
the absence of foreground elements.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

def generate():
    width = random.randint(2, 30)
    height = random.randint(2, 30)
    total = width * height
    n = random.randint(1, min(5, (total - 1) // 2))
    bg_color = random.randint(0, 9)
    input_grid = [[bg_color] * width for _ in range(height)]
    positions = random.sample([(r, c) for r in range(height) for c in range(width)], n)
    for r, c in positions:
        color = random.randint(0, 9)
        while color == bg_color:
            color = random.randint(0, 9)
        input_grid[r][c] = color
    output_grid = [[bg_color] * width for _ in range(height)]
    return {
        "input": input_grid,
        "output": output_grid
    }


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

from collections import Counter
def p(input_grid):
    flat = [pixel for row in input_grid for pixel in row]
    bg_color = Counter(flat).most_common(1)[0][0]
    width = len(input_grid[0])
    height = len(input_grid)
    return [[bg_color] * width for _ in range(height)]
