# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-11
# ---------------------------------------------------------------

"""
Task ID: 6993df60
Difficulty: easy

=== Tags ===
- Pattern coloring
- Even or odd

=== Description ===
The task involves transforming an input grid into an output grid where each
cell's color depends solely on the parity of its row index. Specifically, all
cells in even-indexed rows (0, 2, 4, ...) are set to color 1, while all cells in
odd-indexed rows (1, 3, 5, ...) are set to color 2. The input grid's content is
irrelevant to the transformation—the rule applies uniformly across all rows
regardless of the input values. The output grid will always differ from the
input since the input contains arbitrary colors (0-9) while the output enforces
a strict alternating row pattern.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

def generate():
    while True:
        width = random.randint(1, 30)
        height = random.randint(1, 30)
        input_grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
        output_grid = [[1 if i % 2 == 0 else 2 for _ in range(width)] for i in range(height)]
        if input_grid != output_grid:
            return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    height = len(input_grid)
    width = len(input_grid[0])
    return [[1 if i % 2 == 0 else 2 for _ in range(width)] for i in range(height)]
