# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-03
# ---------------------------------------------------------------

"""
Task ID: 23edb253
Difficulty: hard

=== Tags ===
- Count patterns
- Adapt image to grid
- Even or odd

=== Description ===
The task involves transforming an input grid based on the parity of adjacent
cell pairs. First, count all horizontally and vertically adjacent cell pairs
(sharing the same color value) in the input grid. If this count is even, the
output grid is the input grid flipped horizontally (left-right mirror). If the
count is odd, the output grid is the input grid rotated 90 degrees clockwise.
This requires recognizing adjacency patterns, determining parity, and applying a
transformation that depends on that parity, making it a challenging abstract
reasoning task.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random
from common import flip_horiz
def generate():
    while True:
        width = random.randint(1, 30)
        height = random.randint(1, 30)
        grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
        
        count = 0
        for r in range(height):
            for c in range(width - 1):
                if grid[r][c] == grid[r][c + 1]:
                    count += 1
        for r in range(height - 1):
            for c in range(width):
                if grid[r][c] == grid[r + 1][c]:
                    count += 1
        
        if count % 2 == 0:
            output = flip_horiz(grid)
        else:
            output = [list(x)[::-1] for x in zip(*grid)]
        
        if grid != output:
            return {"input": grid, "output": output}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

from common import flip_horiz
def p(input_grid):
    width = len(input_grid[0])
    height = len(input_grid)
    count = 0
    for r in range(height):
        for c in range(width - 1):
            if input_grid[r][c] == input_grid[r][c + 1]:
                count += 1
    for r in range(height - 1):
        for c in range(width):
            if input_grid[r][c] == input_grid[r + 1][c]:
                count += 1
    
    if count % 2 == 0:
        return flip_horiz(input_grid)
    else:
        return [list(x)[::-1] for x in zip(*input_grid)]
