# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-10
# ---------------------------------------------------------------

"""
Task ID: e595caf2
Difficulty: easy

=== Tags ===
- Detect grid
- Image rotation

=== Description ===
The task involves rotating the input grid 90 degrees clockwise to produce the
output grid. The transformation is a standard geometric rotation where each
element's position shifts according to the rotation rule: the top row of the
input becomes the rightmost column of the output in reverse order, the second
row becomes the second-right column in reverse, and so on. The grid dimensions
change accordingly (e.g., a 3×4 input becomes a 4×3 output). This transformation
is purely visual, requiring no numerical calculations or pattern recognition
beyond the spatial rearrangement of elements. The output grid maintains all
original colors but repositions them through consistent rotation, making it a
straightforward visual abstraction task for easy difficulty.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

def generate():
    import random
    width = random.randint(1, 30)
    height = random.randint(1, 30)
    while width == height:
        width = random.randint(1, 30)
        height = random.randint(1, 30)
    input_grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
    output_grid = [[input_grid[i][j] for i in range(height-1, -1, -1)] for j in range(width)]
    return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    h = len(input_grid)
    w = len(input_grid[0])
    return [[input_grid[i][j] for i in range(h-1, -1, -1)] for j in range(w)]
