# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-11
# ---------------------------------------------------------------

"""
Task ID: 68e90cbe
Difficulty: hard

=== Tags ===
- Cave escape
- Add center crosshair

=== Description ===
Input grids depict a single contiguous cave region (a connected set of non-
background cells) surrounded by a uniform background. The cave's shape varies in
complexity, featuring irregular walls, chambers, and paths, but always forms a
single connected component with a clear minimal bounding box. The output grid
must retain all input features while adding a center crosshair: a '+' pattern
centered within the cave's minimal bounding box. The crosshair consists of the
center cell of the bounding box and its four orthogonal neighbors (up, down,
left, right), all colored with a distinct, high-contrast marker color (e.g.,
orange) that does not appear in the input. The center is calculated as the
midpoint of the bounding box's width and height, with coordinates rounded to the
nearest grid cell (e.g., for a 4×4 bounding box, center at the second
row/column). If a crosshair arm lies outside the cave interior, that arm is
omitted. The marker color must be unique to avoid blending with existing cave
features, ensuring the crosshair remains visually distinct. The transformation
requires identifying the cave's boundaries, computing its bounding box, locating
the center, and verifying that all crosshair cells are part of the cave interior
before applying the marker color.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random
from common import continuous_creature, grid

def generate():
    W = random.randint(3, 30)
    H = random.randint(3, 30)
    input_grid = grid(W, H, 0)
    size = min(random.randint(5, 20), W * H)
    cave_pixels = continuous_creature(size, W, H)
    for r, c in cave_pixels:
        input_grid[r][c] = random.randint(1, 8)
    
    min_r = min(r for r, c in cave_pixels)
    max_r = max(r for r, c in cave_pixels)
    min_c = min(c for r, c in cave_pixels)
    max_c = max(c for r, c in cave_pixels)
    
    center_r = min_r + (max_r - min_r) // 2
    center_c = min_c + (max_c - min_c) // 2
    
    output_grid = [row[:] for row in input_grid]
    for r, c in [(center_r, center_c), (center_r-1, center_c), 
                 (center_r+1, center_c), (center_r, center_c-1), 
                 (center_r, center_c+1)]:
        if 0 <= r < H and 0 <= c < W and input_grid[r][c] != 0:
            output_grid[r][c] = 9
    
    return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    grid = [list(row) for row in input_grid]
    H = len(grid)
    if H == 0:
        return grid
    W = len(grid[0])
    
    # Input uses 1-8, so 9 is guaranteed to be available
    marker_color = 9
    
    cave_pixels = []
    for r in range(H):
        for c in range(W):
            if grid[r][c] != 0:
                cave_pixels.append((r, c))
    
    if not cave_pixels:
        return grid
    
    min_r = min(r for r, c in cave_pixels)
    max_r = max(r for r, c in cave_pixels)
    min_c = min(c for r, c in cave_pixels)
    max_c = max(c for r, c in cave_pixels)
    
    center_r = min_r + (max_r - min_r) // 2
    center_c = min_c + (max_c - min_c) // 2
    
    positions = [(center_r, center_c), (center_r-1, center_c), 
                 (center_r+1, center_c), (center_r, center_c-1), 
                 (center_r, center_c+1)]
    
    for r, c in positions:
        if 0 <= r < H and 0 <= c < W and grid[r][c] != 0:
            grid[r][c] = marker_color
    
    return grid
