# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-08
# ---------------------------------------------------------------

"""
Task ID: 345976a9
Difficulty: easy

=== Tags ===
- Associate colors to colors
- Expand to square canvas

=== Description ===
The task involves transforming an input grid by first swapping all instances of
color 1 with color 2 and vice versa, then expanding the grid to the smallest
possible square by adding rows or columns filled with color 0. The input grid is
always non-square or contains at least one instance of color 1 or 2, ensuring
the output grid differs from the input. The output grid dimensions are
determined by the maximum of the input's height and width, with the original
grid placed in the top-left corner and new cells filled with color 0 (which
remains unchanged after the swap, as 0 is not part of the color mapping). For
example, a 2x3 input becomes a 3x3 output, where all 1s and 2s are swapped and
the added row is filled with 0s.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

def generate():
    width = random.randint(1, 30)
    height = random.randint(1, 30)
    input_grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
    if width == height:
        has_1_or_2 = any(1 in row or 2 in row for row in input_grid)
        if not has_1_or_2:
            r, c = random.randint(0, height-1), random.randint(0, width-1)
            input_grid[r][c] = random.choice([1, 2])
    transformed = [[2 if x == 1 else 1 if x == 2 else x for x in row] for row in input_grid]
    new_size = max(width, height)
    output_grid = [[0] * new_size for _ in range(new_size)]
    for r in range(height):
        for c in range(width):
            output_grid[r][c] = transformed[r][c]
    return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    transformed = [[2 if x == 1 else 1 if x == 2 else x for x in row] for row in input_grid]
    h = len(input_grid)
    w = len(input_grid[0])
    size = max(h, w)
    output = [[0] * size for _ in range(size)]
    for i in range(h):
        for j in range(w):
            output[i][j] = transformed[i][j]
    return output
