# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-06
# ---------------------------------------------------------------

"""
Task ID: 1c1e71b9
Difficulty: easy

=== Tags ===
- Add corner markers

=== Description ===
The input grids are 2D grids of colors (values 0-9) representing abstract
symbols. The output grid is created by replacing the four corner cells (top-
left, top-right, bottom-left, bottom-right) with the fixed color 5 (gray), while
all other cells remain unchanged. The input grids are specifically generated to
ensure none of the corner cells initially contain color 5, guaranteeing the
output grid is always distinct from the input. This task requires recognizing
and modifying the four corner positions without altering any other grid
elements, making it a straightforward visual transformation suitable for an
"easy" difficulty level.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

def generate():
    width = random.randint(1, 30)
    height = random.randint(1, 30)
    input_grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
    corners = []
    if height > 0 and width > 0:
        corners.append((0, 0))
        if width > 1:
            corners.append((0, width-1))
        if height > 1:
            corners.append((height-1, 0))
        if width > 1 and height > 1:
            corners.append((height-1, width-1))
    for r, c in corners:
        if input_grid[r][c] == 5:
            new_color = random.choice([i for i in range(10) if i != 5])
            input_grid[r][c] = new_color
    output_grid = [row[:] for row in input_grid]
    for r, c in corners:
        output_grid[r][c] = 5
    return {
        "input": input_grid,
        "output": output_grid
    }


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    if not input_grid or not input_grid[0]:
        return input_grid
    # Convert to list of lists if input is tuple
    if isinstance(input_grid[0], tuple):
        input_grid = [list(row) for row in input_grid]
    height = len(input_grid)
    width = len(input_grid[0])
    output = [row[:] for row in input_grid]
    corners = [(0, 0)]
    if width > 1:
        corners.append((0, width-1))
    if height > 1:
        corners.append((height-1, 0))
    if width > 1 and height > 1:
        corners.append((height-1, width-1))
    for r, c in corners:
        output[r][c] = 5
    return output
