# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-11
# ---------------------------------------------------------------

"""
Task ID: d2b3e2eb
Difficulty: easy

=== Tags ===
- Extend line to edge

=== Description ===
The input grid consists of a 2D array of integers (0-9), where 0 represents
empty space. Each row contains a single contiguous horizontal segment of a non-
zero color (e.g., 3) that does not touch the left or right edge of the grid. The
output grid extends each such segment to fill the entire row with its color,
resulting in the entire row being uniformly colored. Rows without such segments
remain unchanged (though in the task design, all rows with segments will be
extended). This transformation is deterministic and applies uniformly to all
qualifying rows, requiring no additional reasoning beyond extending the line to
the grid's boundaries.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random
from common import grid
def generate():
    width = random.randint(3, 30)
    height = random.randint(1, 30)
    input_grid = grid(width, height, 0)
    output_grid = grid(width, height, 0)
    
    for r in range(height):
        color = random.randint(1, 9)
        start = random.randint(1, width - 2)
        end = random.randint(start, width - 2)
        for c in range(start, end + 1):
            input_grid[r][c] = color
        for c in range(width):
            output_grid[r][c] = color
    
    return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    height = len(input_grid)
    width = len(input_grid[0])
    output_grid = []
    for r in range(height):
        row = input_grid[r]
        color = 0
        for c in range(width):
            if row[c] != 0:
                color = row[c]
                break
        if color != 0:
            output_grid.append([color] * width)
        else:
            output_grid.append(row[:])
    return output_grid
