# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-08
# ---------------------------------------------------------------

"""
Task ID: 4cdb408f
Difficulty: easy

=== Tags ===
- Two color checkerboard
- Count shapes
- Remove border
- Pattern resizing

=== Description ===
The input grid is a checkerboard pattern alternating between two distinct colors
(e.g., 1 and 2) across all cells. The output grid is generated by removing the
outermost border (all cells in the first and last rows and columns) of the input
grid. This operation reduces the grid dimensions by two in both width and height
(e.g., a 5×5 input becomes a 3×3 output). The "count shapes" aspect refers to
the solver recognizing that the border consists of the outermost connected
shapes (perimeter cells), and "pattern resizing" describes the reduction in grid
size while preserving the internal checkerboard structure. The transformation
strictly follows border removal without modifying colors or shapes within the
grid.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random
def generate():
    width = random.randint(3, 30)
    height = random.randint(3, 30)
    colors = random.sample(range(0, 10), 2)
    input_grid = [[colors[(i + j) % 2] for j in range(width)] for i in range(height)]
    output_grid = [row[1:-1] for row in input_grid[1:-1]]
    return {"input": input_grid, "output": output_grid}



# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input):
    return [row[1:-1] for row in input[1:-1]]

