# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-04
# ---------------------------------------------------------------

"""
Task ID: d66d1a00
Difficulty: medium

=== Tags ===
- Associate colors to colors
- Select every nth column
- Image rotation

=== Description ===
The task involves transforming an input grid into an output grid through three
consecutive operations. First, each color in the input grid is replaced with a
distinct target color according to a fixed substitution rule (e.g., color 1 maps
to 4, color 2 maps to 5, etc.). Second, every nth column (where n is a fixed
integer greater than 1) is retained from the color-mapped grid, starting from
column index 0 (e.g., for n=2, columns 0, 2, 4, ... are kept). Third, the
resulting grid is rotated 90 degrees clockwise. The output grid reflects the
combined effect of these operations, with dimensions adjusted based on the
column selection and rotation. The substitution rule is consistent for all
grids, and the value of n is fixed for the task. The transformation requires
recognizing the color mapping, identifying the column selection pattern, and
applying the rotation.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random

substitution = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
n = 2

def generate():
    width = random.randint(1, 30)
    height = random.randint(1, 30)
    input_grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
    substituted = [[substitution[pixel] for pixel in row] for row in input_grid]
    selected_cols = [i for i in range(0, width, n)]
    selected_grid = [[row[i] for i in selected_cols] for row in substituted]
    rotated = [list(row)[::-1] for row in zip(*selected_grid)]
    return {
        "input": input_grid,
        "output": rotated
    }


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    substitution = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
    n = 2
    substituted = [[substitution[pixel] for pixel in row] for row in input_grid]
    width = len(input_grid[0])
    selected_cols = [i for i in range(0, width, n)]
    selected_grid = [[row[i] for i in selected_cols] for row in substituted]
    rotated = [list(row)[::-1] for row in zip(*selected_grid)]
    return rotated
