# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-08
# ---------------------------------------------------------------

"""
Task ID: 67087371
Difficulty: medium

=== Tags ===
- Pattern modification

=== Description ===
The input is a 2D grid of integers between 0 and 9. Each row in the output grid
is the corresponding row from the input grid shifted cyclically to the right by
the row's index (0-based). For example, the first row (index 0) remains
unchanged, the second row (index 1) shifts right by one position (with wrap-
around), the third row (index 2) shifts right by two positions, and so on. This
transformation ensures that the output grid differs from the input grid for all
valid grid dimensions (ensuring at least two rows and two columns are present to
avoid identity transformations).
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random
def generate():
    while True:
        width = random.randint(2, 30)
        height = random.randint(2, 30)
        input_grid = [[random.randint(0, 9) for _ in range(width)] for _ in range(height)]
        output_grid = []
        for i in range(height):
            shift = i % width
            output_grid.append(input_grid[i][-shift:] + input_grid[i][:-shift])
        if input_grid != output_grid:
            return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    width = len(input_grid[0])
    output = []
    for i, row in enumerate(input_grid):
        shift = i % width
        output.append(row[-shift:] + row[:-shift])
    return output
