# ---------------------------------------------------------------
# This file was automatically generated. DO NOT EDIT MANUALLY.
# 
# Generated by: conor-99/InfiniteARC/prepare.py
# Date: 2025-11-08
# ---------------------------------------------------------------

"""
Task ID: 5c9824f4
Difficulty: easy

=== Tags ===
- Remove singletons

=== Description ===
The task involves transforming an input grid into an output grid by removing all
singleton cells. A singleton cell is defined as a non-zero cell that has no
adjacent cells (up, down, left, or right) sharing the same color. In the output
grid, all such singleton cells are set to 0 (background), while all other cells
retain their original values. The input grid is guaranteed to contain at least
one singleton cell to ensure the output differs from the input. This
transformation requires identifying isolated non-zero cells and eliminating them
through a simple adjacency check, making it an intuitive and accessible task for
beginners.
"""


# ---------------------------------------------------------------
# Generator Code
# ---------------------------------------------------------------

import random
import common

def generate():
    width = random.randint(1, 30)
    height = random.randint(1, 30)
    input_grid = common.grid(width, height, 0)
    r = random.randint(0, height - 1)
    c = random.randint(0, width - 1)
    color = random.randint(1, 9)
    input_grid[r][c] = color
    output_grid = common.grid(width, height, 0)
    return {"input": input_grid, "output": output_grid}


# ---------------------------------------------------------------
# Solver Code
# ---------------------------------------------------------------

def p(input_grid):
    if isinstance(input_grid[0], tuple):
        input_grid = [list(row) for row in input_grid]
    height = len(input_grid)
    width = len(input_grid[0])
    output = [row[:] for row in input_grid]
    for r in range(height):
        for c in range(width):
            if input_grid[r][c] != 0:
                has_neighbor = False
                for dr, dc in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
                    nr, nc = r + dr, c + dc
                    if 0 <= nr < height and 0 <= nc < width and input_grid[nr][nc] == input_grid[r][c]:
                        has_neighbor = True
                        break
                if not has_neighbor:
                    output[r][c] = 0
    return output
